runtime: nodejs16
instance_class: F2

handlers:
- url: /.*
  secure: always
  script: auto

# to connect cloud
env_variables:
  GOOGLE_PROJECT_ID: iswara-project,
  INSTANCE_CONNECTION_NAME: iswara-project:asia-southeast1:iswara,
  DB_PORT: 8080,
  DB_USER: root,
  DB_PASS: admin-iswara276,
  DB_NAME: iswara_data

# beta_settings:
#   cloud_sql_instances: iswara-project:asia-southeast1:iswara